f=ini_open("Musicfx.dll");
global.tutorial = ini_read_real("tutorial","tutorial",0);
//
global.neonEasy = ini_read_real("levelEasy","neon",0);
global.songofplainsEasy = ini_read_real("levelEasy","songofplains",0);
global.sunnydayEasy = ini_read_real("levelEasy","sunnyday",0);
global.discoEasy = ini_read_real("levelEasy","ball",0);
global.natureEasy = ini_read_real("levelEasy","nature",0);
global.crystalEasy = ini_read_real("levelEasy","crystal",0);
global.rhywaveEasy = ini_read_real("levelEasy","rhywave",0);
global.metropolisEasy = ini_read_real("levelEasy","metropolis",0);
global.oursummerendsEasy = ini_read_real("levelEasy","oursummerends",0);
global.deadsilenceEasy = ini_read_real("levelEasy","deadsilence",0);
global.prisonrunEasy = ini_read_real("levelEasy","prisonrun",0);
//
global.neonHard = ini_read_real("levelHard","neon",0);
global.songofplainsHard = ini_read_real("levelHard","songofplains",0);
global.sunnydayHard = ini_read_real("levelHard","sunnyday",0);
global.discoHard = ini_read_real("levelHard","ball",0);
global.natureHard = ini_read_real("levelHard","nature",0);
global.crystalHard = ini_read_real("levelHard","crystal",0);
global.rhywaveHard = ini_read_real("levelHard","rhywave",0);
global.metropolisHard = ini_read_real("levelHard","metropolis",0);
global.oursummerendsHard = ini_read_real("levelHard","oursummerends",0);
global.deadsilenceHard = ini_read_real("levelHard","deadsilence",0);
global.prisonrunHard = ini_read_real("levelHard","prisonrun",0);
//
global.neonoEasy = ini_read_real("levelEasy","neono",0);
global.songofplainsoEasy = ini_read_real("levelEasy","songofplainso",0);
global.sunnydayoEasy = ini_read_real("levelEasy","sunnydayo",0);
global.discooEasy = ini_read_real("levelEasy","ballo",0);
global.natureoEasy = ini_read_real("levelEasy","natureo",0);
global.crystaloEasy = ini_read_real("levelEasy","crystalo",0);
global.rhywaveoEasy = ini_read_real("levelEasy","rhywaveo",0);
global.metropolisoEasy = ini_read_real("levelEasy","metropoliso",0);
global.oursummerendsoEasy = ini_read_real("levelEasy","oursummerendso",0);
global.prisonrunoEasy = ini_read_real("levelEasy","prisonruno",0);
//
global.neonoHard = ini_read_real("levelHard","neono",0);
global.songofplainsoHard = ini_read_real("levelHard","songofplainso",0);
global.sunnydayoHard = ini_read_real("levelHard","sunnydayo",0);
global.discooHard = ini_read_real("levelHard","ballo",0);
global.natureoHard = ini_read_real("levelHard","natureo",0);
global.crystaloHard = ini_read_real("levelHard","crystalo",0);
global.rhywaveoHard = ini_read_real("levelHard","rhywaveo",0);
global.metropolisoHard = ini_read_real("levelHard","metropoliso",0);
global.oursummerendsoHard = ini_read_real("levelHard","oursummerendso",0);
global.prisonrunoHard = ini_read_real("levelHard","prisonruno",0);
//
global.neonDiamond = ini_read_real("levelDiamond","neon",0);
global.songofplainsDiamond = ini_read_real("levelDiamond","songofplains",0);
global.sunnydayDiamond = ini_read_real("levelDiamond","sunnyday",0);
global.discoDiamond = ini_read_real("levelDiamond","ball",0);
global.natureDiamond = ini_read_real("levelDiamond","nature",0);
global.crystalDiamond = ini_read_real("levelDiamond","crystal",0);
global.rhywaveDiamond = ini_read_real("levelDiamond","rhywave",0);
global.metropolisDiamond = ini_read_real("levelDiamond","metropolis",0);
global.oursummerendsDiamond = ini_read_real("levelDiamond","oursummerends",0);
global.deadsilenceDiamond = ini_read_real("levelDiamond","deadsilence",0);
global.prisonrunDiamond = ini_read_real("levelDiamond","prisonrun",0);
//
global.music = ini_read_real("settings","music",1);
global.sound = ini_read_real("settings","sound",1);
global.display = ini_read_real("settings","display",1);
global.language = ini_read_real("settings","language",0);
global.sChinese = ini_read_real("settings","sChinese",0);
//
global.skinOnChoose = ini_read_real("skin","onchoose",1);
global.skinUT = ini_read_real("skin","ut",0);
global.skinMegaman = ini_read_real("skin","megaman",0);
global.skinKirby = ini_read_real("skin","kirby",0);
global.skinGravity = ini_read_real("skin","gravity",0);
global.skinBlood = ini_read_real("skin","blood",0);
//
global.challengeReward1 = ini_read_real("challenge","01reward1",0);
global.challengeReward2 = ini_read_real("challenge","01reward2",0);
global.challengeScoreOne = ini_read_real("challenge","01s1",0);
global.challengeScoreTwo = ini_read_real("challenge","01s2",0);
global.challengeScoreThree = ini_read_real("challenge","01s3",0);
global.challengeScoreFour = ini_read_real("challenge","01s4",0);
global.challenge2Reward1 = ini_read_real("challenge","02reward1",0);
global.challenge2Reward2 = ini_read_real("challenge","02reward2",0);
global.challenge2ScoreOne = ini_read_real("challenge","02s1",0);
global.challenge2ScoreTwo = ini_read_real("challenge","02s2",0);
global.challenge2ScoreThree = ini_read_real("challenge","02s3",0);
global.challenge2ScoreFour = ini_read_real("challenge","02s4",0);
global.challenge3Reward1 = ini_read_real("challenge","03reward1",0);
global.challenge3Reward2 = ini_read_real("challenge","03reward2",0);
global.challenge3ScoreOne = ini_read_real("challenge","03s1",0);
global.challenge3ScoreTwo = ini_read_real("challenge","03s2",0);
global.challenge3ScoreThree = ini_read_real("challenge","03s3",0);
global.challenge3ScoreFour = ini_read_real("challenge","03s4",0);
//
global.note1 = ini_read_real("achievement","note1",0);
global.note2 = ini_read_real("achievement","note2",0);
global.note3 = ini_read_real("achievement","note3",0);
global.note4 = ini_read_real("achievement","note4",0);
global.note5 = ini_read_real("achievement","note5",0);
global.note6 = ini_read_real("achievement","note6",0);
global.note7 = ini_read_real("achievement","note7",0);
global.note8 = ini_read_real("achievement","note8",0);
global.note9 = ini_read_real("achievement","note9",0);
global.note10 = ini_read_real("achievement","note10",0);
global.note11 = ini_read_real("achievement","note11",0);
global.ach1 = ini_read_real("achievement","ach1",0);
global.ach2 = ini_read_real("achievement","ach2",0);
global.ach3 = ini_read_real("achievement","ach3",0);
global.ach4 = ini_read_real("achievement","ach4",0);
global.ach5 = ini_read_real("achievement","ach5",0);
global.ach6 = ini_read_real("achievement","ach6",0);
global.ach7 = ini_read_real("achievement","ach7",0);
global.ach8 = ini_read_real("achievement","ach8",0);
global.ach9 = ini_read_real("achievement","ach9",0);
global.ach10 = ini_read_real("achievement","ach10",0);
global.ach11 = ini_read_real("achievement","ach11",0);
global.ach12 = ini_read_real("achievement","ach12",0);
global.ach13 = ini_read_real("achievement","ach13",0);
global.tro1 = ini_read_real("achievement","tro1",0);
global.tro2 = ini_read_real("achievement","tro2",0);
global.tro3 = ini_read_real("achievement","tro3",0);
//
global.neonold = ini_read_real("pUnlock","neonold",0);
global.deadsilenceUnlock = ini_read_real("pUnlock","deadsilence",0);
global.minilevel1 = ini_read_real("pUnlock","minilevel1",0);
global.neonoldLevel = ini_read_real("pLevel","neonold",0);
global.neonoldDiamond = ini_read_real("pLevelDiamond","neonold",0);
//
global.rDiamond1 = ini_read_real("sprFesEvent","rDiamond1",0);
global.rDiamond2 = ini_read_real("sprFesEvent","rDiamond2",0);
global.rDiamond3 = ini_read_real("sprFesEvent","rDiamond3",0);
global.rDiamond4 = ini_read_real("sprFesEvent","rDiamond4",0);
global.rDiamond5 = ini_read_real("sprFesEvent","rDiamond5",0);
global.rDiamond6 = ini_read_real("sprFesEvent","rDiamond6",0);
global.rDiamond7 = ini_read_real("sprFesEvent","rDiamond7",0);
global.rDiamond8 = ini_read_real("sprFesEvent","rDiamond8",0);
global.rDiamond9 = ini_read_real("sprFesEvent","rDiamond9",0);
global.rDiamond10 = ini_read_real("sprFesEvent","rDiamond10",0);
global.rReward1 = ini_read_real("sprFesEvent","rReward1",0);
global.rReward2 = ini_read_real("sprFesEvent","rReward2",0);
global.rReward3 = ini_read_real("sprFesEvent","rReward3",0);
global.rReward4 = ini_read_real("sprFesEvent","rReward4",0);
global.rReward5 = ini_read_real("sprFesEvent","rReward5",0);
global.rReward6 = ini_read_real("sprFesEvent","rReward6",0);
global.rReward7 = ini_read_real("sprFesEvent","rReward7",0);
global.rReward8 = ini_read_real("sprFesEvent","rReward8",0);
global.rReward9 = ini_read_real("sprFesEvent","rReward9",0);
global.rReward10 = ini_read_real("sprFesEvent","rReward10",0);
//
global.death = ini_read_real("death","death",0);
global.coin = ini_read_real("coin","coin",0);
//
ini_close();
if global.taptap==1 {global.language=3;global.sChinese=1;}
